"""Tool to manually merge multi-GPU feature extraction shards for PlantCLEF 2026.

This script combines the .pt shards generated by trainer.py into a single 
monolithic feature cache for Phase 2A (MLP Warmup) and PCA fitting.
"""

import os
import sys
import glob
import torch
import argparse
from tqdm import tqdm
from pathlib import Path

# Add workspace root to path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))
from src import config as scfg

def parse_args():
    parser = argparse.ArgumentParser(description="PLANTCLEF Shard Merger")
    parser.add_argument("--keep-bf16", action="store_true", help="Keep features in BF16 (Saves 50% disk space, ~18GB total)")
    parser.add_argument("--expected-samples", type=int, default=1408033, help="Expected total sample count for integrity check")
    return parser.parse_args()

def merge_shards():
    args = parse_args()
    shard_dir = f"{config.FEATURE_CACHE_PATH}_shards"
    out_path = config.FEATURE_CACHE_PATH
    
    print(f"\n" + "="*60)
    print(f" PLANTCLEF MERGE: Combining Feature Shards (PlantCLEF 2026)")
    print(f"="*60)
    print(f"Target Directory: {shard_dir}")
    
    # plantclef: Find all shards across all ranks
    shard_files = sorted(glob.glob(os.path.join(shard_dir, "shard_rank*.pt")))
    
    if not shard_files:
        print(f"[Error] No shards found in {shard_dir}!")
        return
        
    print(f"Found {len(shard_files)} shards. Initializing RAM buffer...")
    
    # 1. Initialize buffer using keys from first shard
    try:
        first_shard = torch.load(shard_files[0], weights_only=False, map_location='cpu')
        merged = {k: [] for k in first_shard.keys()}
        del first_shard
    except Exception as e:
        print(f"[Error] Failed to read first shard: {e}")
        return
    
    # 2. Sequential Load
    for path in tqdm(shard_files, desc="Merging Shards"):
        try:
            shard = torch.load(path, weights_only=False, map_location='cpu')
            for k in merged:
                if k in shard:
                    merged[k].append(shard[k])
            del shard
        except Exception as e:
            print(f"\n[Warning] Failed to load {path}: {e}. Skipping...")
        
    # 3. Concatenation and Type Conversion
    print(f"\nConcatenating tensors (Mode: {'BF16' if args.keep_bf16 else 'FP32'})...")
    cache = {}
    for k, v in merged.items():
        if not v: continue
        t = torch.cat(v)
        
        # plantclef: Labels stay as Long, features convert to Float32 unless --keep-bf16
        if k == 'labels':
            cache[k] = t.long()
        else:
            cache[k] = t if args.keep_bf16 else t.float()
        
    total_samples = len(cache.get('labels', []))
    print(f"Total Samples Merged: {total_samples:,}")
    
    # 4. Integrity Check
    if total_samples != args.expected_samples:
        diff = total_samples - args.expected_samples
        print(f"\n" + "!"*60)
        print(f" INTEGRITY WARNING: Sample count mismatch!")
        print(f" Expected: {args.expected_samples:,}")
        print(f" Actual:   {total_samples:,}")
        print(f" Difference: {diff:+,}")
        print("!"*60 + "\n")
    else:
        print(f"[Success] Sample count matches expected dataset size.")

    # 5. Atomic Atomic Write
    tmp_path = out_path + ".tmp"
    print(f"Saving final cache to: {out_path} ...")
    try:
        torch.save(cache, tmp_path)
        os.replace(tmp_path, out_path)
        print(f"=== MERGE COMPLETE ===")
        print(f"Final Size: {os.path.getsize(out_path) / 1024**3:.2f} GB")
        print(f"Next Step: Launch Phase 2A (MLP Warmup) via ./plantclef.py train --phase p2a")
    except Exception as e:
        print(f"[Error] Failed to save merged cache: {e}")
        if os.path.exists(tmp_path):
            os.remove(tmp_path)

if __name__ == "__main__":
    merge_shards()
